### ISSUE TITLE
Видалити папку .idea

### ISSUE THREAD

**Issue by das13** [konnor2134/TaskManager-project#1]
В ремозиторії не повинно бути "службових" данних, таких як .idea? target і т.п. Тому потрібно видалити з репозиторія папку **.idea**

**Comment by konnor2134** [comment]
fda3e

**Comment by konnor2134** [comment]
#3

**Comment by konnor2134** [comment]
fda3e5fa9d8fc0ca37e5303d80fd8a20e910475d
