### ISSUE TITLE
Додати скрипти

### ISSUE THREAD

**Issue by das13** [konnor2134/TaskManager-project#2]
В проекті повинні бути скрипти компіляції та запуску. Їх потрібно додати.

**Comment by konnor2134** [comment]
Я правильно зрозумів, потрібно створити скрипти, що будуть "збирати" проект в файл, і потім запускати його. Чи можливо просто через javac його скомпілювати та через java запустити?

**Comment by konnor2134** [comment]
#4

**Comment by konnor2134** [comment]
#4

**Comment by konnor2134** [comment]
[https://github.com/konnor2134/Lab1/commit/5217c20bc4465d432407593e023a72d3825ca9fa](url)

**Comment by konnor2134** [comment]
[](https://github.com/konnor2134/Lab1/commit/5217c20bc4465d432407593e023a72d3825ca9fa)

**Comment by konnor2134** [comment]
5217c20bc4465d432407593e023a72d3825ca9fa
