### ISSUE TITLE
Допрацювати календар

### ISSUE THREAD

**Issue by das13** [konnor2134/TaskManager-project#20]
До початку завдання ще 2 хв, а каленар показує, що завдань немає:
![изображение](https://user-images.githubusercontent.com/10417869/180596286-1f844aaf-2eae-4836-95d3-eeb438191680.png)

**Comment by konnor2134** [comment]
![image](https://user-images.githubusercontent.com/63258440/180615342-25fbd19f-3e83-47d2-aea3-84d760b8754b.png)
Проблеми не виявив
