### ISSUE TITLE
Порівняння об'єктів

### ISSUE THREAD

**Issue by das13** [konnor2134/TaskManager-project#21]
В **ua.edu.sumdu.j2se.budko.tasks.model.LinkedTaskList.Itr.remove** використовується порівняння об'єктів:
`if (next == lastReturned)`
Це дійсно правильно, чи можливо потрібно використовувати **equals()**

**Comment by konnor2134** [comment]
Equals буде краще
6922195882253bcd84f1b0e55215728ebd1cb90f
