### ISSUE TITLE
[NOTIFY] Пустий блок catch

### ISSUE THREAD

**Issue by das13** [konnor2134/TaskManager-project#8]
В `ua.edu.sumdu.j2se.budko.tasks.controller.NotificationThread.run` пустий блок **catch**. Так робити не правльно. Потрібно принаймні записувати в логгер сповіщення про помилку.
І взагалі відловлювати NPE не зовсім правильно. Краще просто перевірини на нерівність **null**
Аналогічно в `ua.edu.sumdu.j2se.budko.tasks.controller.Controller.addTask()`

**Comment by konnor2134** [comment]
Змінив блок catch в NotificationThread.run. В Controller.addTask() блок catch служить реалізацією виходу з додавання задачі.
aab5e587f4a8dfb051ae94810f25521666739405
